wandb_version: 1

DROPOUT_RATE:
  desc: null
  value: 0.2147087234839637
LEARNING_RATE:
  desc: null
  value: 0.004955219137198704
N_DENSE_1:
  desc: null
  value: 32
N_DENSE_2:
  desc: null
  value: 64
REGULARIZATION_RATE:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.7
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690872755.465589
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.16
      5: 0.15.7
      8:
      - 1
      - 3
      - 5
      10:
      - 9
