wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.7
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690914883.123783
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      3:
      - 23
      4: 3.9.16
      5: 0.15.7
      8:
      - 1
      - 3
      - 5
